### PR TITLE
Implement (set|with)context to bundle arguments to IOContext

### PR DESCRIPTION
**Pull request by fredrikekre**
Implement `IOContextThingy` (placeholder) to bundle arguments to `IOContext` with an object.

### CODE REVIEW

**Comment by tkf** [comment]
This totally makes sense, but I have no idea how to name the `IOContextThingy`. Hmm.... let's call it `IOContextCarrier` unless you have other ideas.

**Comment by fredrikekre** [comment]
Updated to `IOContextCarrier`.

**Comment by fredrikekre** [comment]
bump

**Comment by mortenpi** [comment]
Just throwing two ideas out here:

* I often use the other `DisplayAs` objects with `|>`, e.g.

  ```julia
  myplot |> DisplayAs.PNG
  ```

  So it might be nice if we could use `IOContextCarrier` the same way:

  ```julia
  myobj |> IOContextCarrier(:limit => 2)
  ```

  That would require something like `IOContextCarrier(kv::Pair...) = (x -> IOContextCarrier(x, kv...))`, although that would conflict with the current method I think. Could `IOContextCarrier` use keyword arguments, instead of `Pair`s?

* Bikeshedding the name: `DisplayAs.IOContextCarrier` is pretty long. Maybe `DisplayAs.IOCtx`? Or, if we'd want to be evil, it could also be `DisplayAs.IOContext` -- I think the is kind of a precedent with `DisplayAs.HTML`?

**Comment by fredrikekre** [comment]
Could also be implemented as a callable struct then instead of returning an anonymous function. I don't mind `DisplayAS.IOContext`, what do you think @tkf?

**Comment by tkf** [comment]
Thanks for the ping. Sorry, forgot about this PR. Yes, I agree `IOContextCarrier` is rather long and not super pretty. But I worry that `DisplayAs.IOContext` can be confusing since its instance is not really an `IOContext` (and `IO`).

Actually, we don't need to use the type names as API. How about

```julia
DisplayAs.setcontext(obj, kvs::Pair...) = IOContextCarrier(obj, kvs...)
DisplayAs.withcontext(kvs::Pair...) = obj -> IOContextCarrier(obj, kvs...)
```

(where `IOContextCarrier` is just an internal type)? I want to separate out the curried version as it's reasonable to want to use this for IO-contextualizing a `Pair`.

**Comment by fredrikekre** [comment]
I implemented the proposed changes. CI config is outdated here, do you want me to update that?

**Comment by tkf** [comment]
Thanks a lot for your patience! And sorry for the very slow process.

**Comment by fredrikekre** [comment]
No worries. Can you make a new release too? Thanks.

**Pull request merged**
